M3 migration with custom theme
google-developer-training/basic-android-kotlin-compose-training-lemonade pull request #6
Opened 2023-04-05 19:51 UTC by OwenScott-GDS

2023-04-05 20:52 UTC, yenerm reviewed
lgtm

2023-04-05 20:52 UTC, yenerm commented on app/src/main/java/com/example/lemonade/MainActivity.kt
> +fun LemonApp() {
LemonadeApp?

2023-04-05 20:52 UTC, yenerm commented on app/src/main/java/com/example/lemonade/ui/theme/Theme.kt
> +    useDarkTheme: Boolean = isSystemInDarkTheme(),
I think we disable this and add a comment on this

2023-04-05 20:58 UTC, MagicalMeghan commented on app/src/main/java/com/example/lemonade/MainActivity.kt
> +fun LemonApp() {
+1

2023-04-05 20:58 UTC, MagicalMeghan commented on app/src/main/java/com/example/lemonade/MainActivity.kt
> +                title = { Text(text = "Lemonade",
Text should be on a new line

2023-04-05 20:58 UTC, MagicalMeghan commented on app/src/main/java/com/example/lemonade/MainActivity.kt
> +        modifier = modifier.fillMaxSize()
pass in fillMaxSize() from parent

2023-04-05 20:58 UTC, MagicalMeghan commented on app/src/main/java/com/example/lemonade/MainActivity.kt
> +            fontSize = 18.sp
assign to something in Type.kt and assign it here instead of setting the fontSize

2023-04-27 18:08 UTC, yenerm requested changes

2023-04-27 18:08 UTC, yenerm commented on app/src/main/java/com/example/lemonade/ui/theme/Theme.kt
> +    dynamicColor: Boolean = false,
Can you add a similar comment like we did in other projects?

2023-04-27 18:08 UTC, yenerm commented on app/src/main/res/values/colors.xml
>      <color name="white">#FFFFFFFF</color>
do we need colors here?

2023-04-27 18:08 UTC, yenerm commented on app/src/main/res/values/colors.xml
> +</resources>
nit: no need to remove empty line eof

2023-05-10 20:53 UTC, merged